#PBS -q vsmp
#PBS -l nodes=1:ppn=48:vsmp

set echo

export PATH=/opt/ScaleMP/mpich2/1.3.2/bin:$PATH
export VSMP_PLACEMENT=PACKED
export VSMP_VERBOSE=YES
export VSMP_MEM_PIN=YES
vsmputil --unpinall

DIR="gridweaver/runtimelib"
EXEC="test"

#move to my $SCRATCH directory
cd /oasis/scratch/$USER/$PBS_JOBID

#copy executable to scratch
cp $HOME/$DIR/$EXEC .

#run my executable
mpirun_rsh -np $PBS_NCPUS -hostfile $PBS_NODEFILE $EXEC

